#Pipeline Analysis Workflow
#Code generated by Loren Suite
#06/01/2021

#The Pipeline Analysis Workflow EmpowerIT file must be run first to extract the most updated tsp5_demand file.

#Import applicable libraries

import win32com.client as win32
from win32com.client import DispatchEx
import openpyxl
import pandas as pd
import openpyxl
from openpyxl import workbook
from openpyxl.utils import get_column_letter
from openpyxl.styles import Alignment
from openpyxl.cell import Cell
import random
from copy import copy
import time
import pynput
from pynput.keyboard import Key, Controller
keyboard = Controller()

import logging
logging.basicConfig(filename='pipelineanalysis.log', level=logging.INFO)

from openpyxl.formula.translate import Translator

from win32com.client import constants

logging.info('Script Initialized.')
#Import library, record, and print the date of the workflow execution.
from datetime import date
today = date.today()
newDate = today.strftime("%Y%m%d")
print("Today's date:", newDate)


#Creates variable for the necessary file destinations.
tsp5_file = 'C:\\Users\\Administrator\\Downloads\\tsp5_demand.xlsx'
PL_file = 'C:\\Users\\Administrator\\Downloads\\PL 20210716 Workflow.xlsx'
updated_file = 'C:\\Users\\Administrator\\Downloads\\PL_Updated_Workflow.xlsx'
tsp5_updated = 'C:\\Users\\Administrator\\Downloads\\tsp5_updated.xlsx'
pl_template = 'C:\\Users\\Administrator\\Downloads\\No_Named_Ranges_Template.xlsx'
pl_merged = 'C:\\Users\\Administrator\\Downloads\\PL_Merged.xlsx'
pl_template_rows = 'C:\\Users\\Administrator\\Downloads\\PL_rows.xlsx'
test_copy_merge = 'C:\\Users\\Administrator\\Downloads\\copy_merge.xlsx'
data_only = 'C:\\Users\\Administrator\\Downloads\\data_only.xlsx'
updated_file = 'C:\\Users\\Administrator\\Downloads\\PL_Updated_Workflow.xlsx'

#Dispatches the Excel application for future commands.
excel = win32.gencache.EnsureDispatch('Excel.Application')

#Autofills the formulas to cover the number of columns needed based on the quantity of opportunity numbers.
excel.Visible = True
wt = excel.Workbooks.Open(updated_file)
ws = wt.Worksheets['PL '+newDate]
excel.AskToUpdateLinks= False

ws.Range('C17').Select()
excel.Selection.AutoFill(ws.Range('C17:C'+ str(baseRows+15)),win32.constants.xlFillDefault)
wt.Save()
excel.Application.Quit()

excel.DisplayAlerts = False
excel.AskToUpdateLinks = False
#test = openpyxl.load_workbook(updated_file, read_only = True)

